name: Push-to-EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

      - name: Post-deploy: sync and restart services
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            # Ensure the target dir exists
            mkdir -p "${{ secrets.TARGET_DIR }}"
            # Sync updated build artifacts (adjust paths if your build output location differs)
            rsync -a --delete ~/app/backend/dist/ "${{ secrets.TARGET_DIR }}/backend/"
            rsync -a --delete ~/app/frontend/dist/ "${{ secrets.TARGET_DIR }}/frontend/"
            rsync -a --delete ~/app/shared/ "${{ secrets.TARGET_DIR }}/shared/"

            # Restart your backend service and reload Caddy
            sudo systemctl restart clue3-app
            sudo systemctl reload caddy
